name: test
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
        - 26.3
        - 28.2
        - 29.4
        - snapshot

    steps:
    - uses: actions/checkout@v2

    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Install Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.9"
          architecture: "x64"

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rust-analyzer

    - name: Install other depedencies
      run: |
           pip3 install python-lsp-server autopep8 rope pycodestyle pyflakes pydocstyle mccabe pylint
           sudo apt-get install clangd
           ln -sf `rustup which --toolchain stable rust-analyzer` ~/.cargo/bin/rust-analyzer

    - name: Build eglot
      run: make compile

    - name: Test eglot
      run: |
        make eglot-check

    - name: Setup debugging tmate session maybe
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
